#!/usr/bin/env bash
# Generate AGENTS.md from agents/rules/*.md.
#
#   scripts/sync-agents.sh                      harness AGENTS.md
#   scripts/sync-agents.sh --client <dir>       client AGENTS.md (harness block + client rules)
#   scripts/sync-agents.sh --check [--client d] exit 1 if the generated file is out of date
#
# Rules are concatenated in filename order. Files matching *sessions* are not
# embedded (they grow); a pointer line is appended instead. Never edit AGENTS.md
# by hand.
set -euo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLIENT_DIR=""
CHECK=0

while [ $# -gt 0 ]; do
  case "$1" in
    --client) CLIENT_DIR="$(cd "$2" && pwd)"; shift 2 ;;
    --check)  CHECK=1; shift ;;
    -h|--help) sed -n '2,11p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

emit_rules() {
  # $1 = repo dir, $2 = heading level prefix ("" or "#")
  local dir="$1" prefix="$2" f
  for f in "$dir"/agents/rules/*.md; do
    [ -e "$f" ] || continue
    case "$(basename "$f")" in *sessions*) continue ;; esac
    if [ -n "$prefix" ]; then
      # demote headings by one level inside the embedded block
      sed -E 's/^(#+) /\1# /' "$f"
    else
      cat "$f"
    fi
    printf '\n\n'
  done
}

sessions_pointer() {
  local dir="$1" f
  for f in "$dir"/agents/rules/*sessions*.md; do
    [ -e "$f" ] || continue
    printf 'Session log (history, read on demand): `agents/rules/%s`\n' "$(basename "$f")"
  done
}

generate() {
  printf '<!-- GENERATED by scripts/sync-agents.sh from agents/rules/*.md. Do not edit. -->\n\n'
  if [ -z "$CLIENT_DIR" ]; then
    printf '# Agent instructions (harness)\n\n'
    emit_rules "$HARNESS_DIR" ""
    sessions_pointer "$HARNESS_DIR"
  else
    printf '# Agent instructions (client project)\n\n'
    printf 'This file embeds the harness rules first, then the client rules. The harness is the parent workspace; its tools and skills apply here.\n\n'
    printf '# Harness rules\n\n'
    emit_rules "$HARNESS_DIR" "#"
    printf '# Client rules\n\n'
    emit_rules "$CLIENT_DIR" "#"
    sessions_pointer "$CLIENT_DIR"
  fi
}

TARGET_DIR="${CLIENT_DIR:-$HARNESS_DIR}"
TARGET="$TARGET_DIR/AGENTS.md"
TMP="$(mktemp)"
generate > "$TMP"

if [ "$CHECK" -eq 1 ]; then
  if [ -f "$TARGET" ] && cmp -s "$TMP" "$TARGET"; then
    echo "AGENTS.md up to date: $TARGET"; rm -f "$TMP"; exit 0
  fi
  echo "AGENTS.md is out of date: $TARGET (run $(basename "$0")${CLIENT_DIR:+ --client <dir>})" >&2
  rm -f "$TMP"; exit 1
fi

mv "$TMP" "$TARGET"
echo "wrote $TARGET ($(wc -l < "$TARGET") lines)"
